### ISSUE TITLE
thread 'trk' panicked at 'internal error: entered unreachable code', src/tracker/dht/rt.rs:396:17

### ISSUE THREAD

**Issue by ArniDagur** [Luminarys/synapse#148]
Here is the full activity log with `RUST_BACKTRACE=full`:
```
torrent@arni-pc ~ $ RUST_BACKTRACE=full synapse
09/05/19 22:38:22 [synapse::init:24] I: Initializing
09/05/19 22:38:22 [synapse::config:173] I: Loaded config file
09/05/19 22:38:23 [synapse:112] I: Initialized, starting!
09/05/19 22:38:23 [synapse::rpc::processor:92] I: user data could not be read from disk, creating a fresh version: No such file or directory (os error 2)
09/05/19 22:38:23 [synapse::rpc:603] I: RPC SSL parameters not specified, using insecure connections!
09/05/19 22:38:23 [synapse::tracker::dht::rt:102] I: Loaded 23 dht buckets, 184 nodes
09/05/19 22:38:23 [synapse::tracker::dht:57] I: Attempting DHT bootstrap!
09/05/19 22:39:26 [synapse::torrent:878] I: Torrent E057A8A80EE5656AAEC05333CBCFED62FAC8C7B7 completed!
09/05/19 22:39:53 [synapse::torrent:878] I: Torrent 132E4AB0B1E7D4D27B2C0B30F4BEE1868460ADF2 completed!
09/05/19 22:45:25 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/05/19 22:49:27 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/05/19 22:52:12 [synapse::torrent:878] I: Torrent D633E91514FBFC4A2A3DCB698738F8F8367E7814 completed!
09/05/19 22:57:01 [synapse::torrent:878] I: Torrent B86633733BAD7B2C0BFF857F6739191203E41E05 completed!
09/05/19 23:00:56 [synapse::torrent:878] I: Torrent 86E2BB24A2F095ECF6470607C652246098D5A987 completed!
09/05/19 23:09:33 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/05/19 23:13:16 [synapse::torrent:878] I: Torrent B12F143BA99900E8A1754809211AD42E11F38AF3 completed!
09/05/19 23:19:37 [synapse::torrent:878] I: Torrent 4D08D4BA6AA182CE3D256B69E97576C5B68235C2 completed!
09/05/19 23:36:38 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/05/19 23:36:39 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/05/19 23:37:45 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/05/19 23:52:43 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/05/19 23:57:45 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 00:00:45 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 00:00:45 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 00:41:51 [synapse::torrent:569] E: Failed to query tracker http://nyaa.tracker.wf:7777/announce: tracker timeout
09/06/19 00:41:51 [synapse::torrent:569] E: Failed to query tracker http://nyaa.tracker.wf:7777/announce: tracker timeout
09/06/19 00:41:52 [synapse::torrent:569] E: Failed to query tracker http://open.nyaatorrents.info:6544/announce: tracker dns invalid
09/06/19 00:45:23 [synapse::torrent:569] E: Failed to query tracker http://nyaa.tracker.wf:7777/announce: tracker timeout
09/06/19 00:45:23 [synapse::torrent:569] E: Failed to query tracker http://open.nyaatorrents.info:6544/announce: tracker dns invalid
09/06/19 00:46:40 [synapse::torrent:878] I: Torrent 9122AE29D319ACE6EE4B660629E46192B07A9250 completed!
09/06/19 01:03:14 [synapse::torrent:878] I: Torrent 6F1F299B778B6BB7F37CCE74F5A6156DFD410579 completed!
09/06/19 01:05:06 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 01:14:09 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 01:19:36 [synapse::torrent:878] I: Torrent EF0B099EB6B85118D7B384C2C4B693D7FED6E1E5 completed!
09/06/19 01:20:16 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 01:20:17 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 01:29:27 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 01:29:27 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 01:58:23 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 01:59:35 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 02:40:49 [synapse::torrent:569] E: Failed to query tracker udp://tracker.internetwarriors.net:1337/announce: tracker timeout
09/06/19 02:40:49 [synapse::torrent:569] E: Failed to query tracker udp://tracker.internetwarriors.net:1337/announce: tracker timeout
09/06/19 03:10:48 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 03:34:54 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 03:48:59 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 03:49:21 [synapse::torrent:878] I: Torrent DF08C122F701D82E201CBF712E822000B1B56250 completed!
09/06/19 03:50:58 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 04:09:05 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 04:24:11 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 04:46:14 [synapse::torrent:878] I: Torrent 2919D38F435EEE33E0E4A27E4D8B0509AF85CFCB completed!
09/06/19 05:06:25 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 05:06:25 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 05:06:33 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 05:38:35 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 05:47:38 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 06:13:48 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 07:39:16 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 07:41:18 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 07:43:17 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 08:20:26 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 08:47:33 [synapse::torrent:878] I: Torrent 678C4AC3FA4B29B1D427F76D833976B572DAFDEF completed!
09/06/19 09:37:52 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 09:54:10 [synapse::torrent:569] E: Failed to query tracker udp://tracker.internetwarriors.net:1337/announce: tracker timeout
09/06/19 13:15:07 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
09/06/19 13:43:03 [synapse::tracker::dht:156] E: Failed to send message on UDP socket: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
thread 'trk' panicked at 'internal error: entered unreachable code', src/tracker/dht/rt.rs:396:17
stack backtrace:
   0:     0x56487d1ad956 - backtrace::backtrace::libunwind::trace::hfe5db90796807973
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x56487d1ad956 - backtrace::backtrace::trace_unsynchronized::h34b865a835594335
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x56487d1ad956 - std::sys_common::backtrace::_print::h527254ae44989167
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x56487d1ad956 - std::sys_common::backtrace::print::he85dd5ddddf46503
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x56487d1ad956 - std::panicking::default_hook::{{closure}}::h847a2eb38b396f14
                               at src/libstd/panicking.rs:200
   5:     0x56487d1ad0d7 - std::panicking::default_hook::h2ca0f9a30a0e206b
                               at src/libstd/panicking.rs:214
   6:     0x56487d1ad0d7 - std::panicking::rust_panic_with_hook::hffcefc09751839d1
                               at src/libstd/panicking.rs:477
   7:     0x56487cf3e064 - std::panicking::begin_panic::h1012a704004408b0
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
   8:     0x56487d08a796 - synapse::tracker::dht::rt::RoutingTable::handle_resp::hbec737b5a9b4801e
                               at src/tracker/dht/rt.rs:396
   9:     0x56487d08a796 - synapse::tracker::dht::Manager::readable::hca1b11d688776148
                               at src/tracker/dht/mod.rs:95
  10:     0x56487d0a7103 - synapse::tracker::Tracker::handle_socket::hda826eabb4ad879e
                               at src/tracker/mod.rs:299
  11:     0x56487d0a7103 - synapse::tracker::Tracker::handle_event::h9dc69c5cff715bba
                               at src/tracker/mod.rs:170
  12:     0x56487cffc7d9 - synapse::tracker::Tracker::run::h3501ab69785e8bab
                               at src/tracker/mod.rs:138
  13:     0x56487cffc7d9 - synapse::tracker::Tracker::start::{{closure}}::he598f0bb193dd80f
                               at src/tracker/mod.rs:114
  14:     0x56487cffc7d9 - synapse::handle::Handle<I,O>::run::{{closure}}::h6e2bc9edf8e9bd3e
                               at src/handle.rs:39
  15:     0x56487cf2f646 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc056efa5f515e906
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/sys_common/backtrace.rs:77
  16:     0x56487cf41109 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h87433e7384c193cc
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/mod.rs:470
  17:     0x56487cf41109 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4c8d4a2209d81222
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:315
  18:     0x56487cf41109 - std::panicking::try::do_call::h3117d94d4fd89332
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:296
  19:     0x56487cf41109 - std::panicking::try::h938b3bc5b4826bac
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b//src/libpanic_unwind/lib.rs:82
  20:     0x56487cf41109 - std::panic::catch_unwind::h617d7e8293a65f8a
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  21:     0x56487cf41109 - std::thread::Builder::spawn_unchecked::{{closure}}::hd505d2facae29ac2
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/mod.rs:469
  22:     0x56487cf41109 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hfce4fac71ec82b13
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  23:     0x56487d1bc23f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  24:     0x56487d1be39c - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  25:     0x56487d1be39c - std::sys_common::thread::start_thread::h2613204ce513782e
                               at src/libstd/sys_common/thread.rs:13
  26:     0x56487d1be39c - std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
                               at src/libstd/sys/unix/thread.rs:79
  27:     0x7f8bb0008397 - start_thread
  28:     0x7f8baff1b68f - __clone
  29:                0x0 - <unknown>
09/06/19 14:29:29 [synapse::control:145] E: crashed thread detected, terminating!
09/06/19 14:29:30 [synapse::init:41] E: Unclean shutdown detected, terminating
```

**Comment by Luminarys** [comment]
DHT code almost certainly still has some issues in it I'll take a look at it.

**Comment by Luminarys** [comment]
Yea culprit seems like some blatantly wrong assumptions made in dht. I'll patch this up.

**Comment by Luminarys** [comment]
Should be fixed.
