### ISSUE TITLE
thread 'trk' panicked at 'internal error: entered unreachable code' (in Tracker::handle_socket)

### ISSUE THREAD

**Issue by whitequark** [Luminarys/synapse#99]
Commit db127ade75b9f72ac86e1a916559a963beb1ab55.
```
thread 'trk' panicked at 'internal error: entered unreachable code', src/tracker/mod.rs:273:13
```
After this, there seems to be a cascading failure, with a lot of messages like this differing only by timestamp:
```
03/21/18 00:02:28 [synapse::control:235] E: tracker error: Error(Channel("Couldn\'t send to trk chan"), State { next_error: None })
```
I'm not sure how to reproduce it reliably. I'll add a backtrace next time it happens.

**Comment by whitequark** [comment]
Full backtrace:
```
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:537
   6: synapse::tracker::Tracker::handle_event
             at src/tracker/mod.rs:273
             at src/tracker/mod.rs:165
   7: synapse::tracker::Tracker::run
             at src/tracker/mod.rs:133
```
This appears to happen when the network link goes down.

**Comment by Luminarys** [comment]
Thanks for the report. There definitely is some sloppiness around network error handling, I'll probably be cleaning things up soon ish.

**Comment by Luminarys** [comment]
I can't seem to reproduce the situation, however I have pushed a fix and generally improved network handling.
